language: python

python:
  - "2.7"
  - "3.2"
  #- "3.3"
  #- "3.4"
  #- "3.5"
  #- "3.5-dev"
  #- "3.6-dev"
  #- "nightly"

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qy install apt-transport-https curl
  - echo 'deb https://packagecloud.io/waghanza/plunder/ubuntu/ trusty main' | sudo tee /etc/apt/sources.list.d/plunder.list
  - sudo curl -sSL https://packagecloud.io/waghanza/plunder/gpgkey | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get -qy install libui libgtk-3-0
  - sudo ln -sfv `readlink -f `sudo find / -type l -name libui.so`` `python -c "import sysconfig;print(sysconfig.get_config_var('LIBDIR'))"`

install: sudo pip install tox-travis coverage

script:
  - python -m unittest

after_success:
  - bash <(curl -s https://codecov.io/bash)
